# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_new', models.BooleanField()),
                ('size', models.CharField(max_length=40)),
                ('instructions', models.TextField()),
                ('featured_photo', models.ImageField(upload_to='')),
                ('category', models.CharField(choices=[('beds', 'Beds & mattressess'), ('furn', 'Furniture, wardrobes & shelves'), ('sofa', 'Sofas & armchairs'), ('table', 'Tables & chairs'), ('texti', 'Textiles'), ('deco', 'Decoration & mirrors'), ('light', 'Lighting'), ('cook', 'Cookware'), ('tablw', 'Tableware'), ('taps', 'Taps & sinks'), ('org', 'Organisers & storage accesories'), ('toys', 'Toys'), ('leis', 'Leisure'), ('safe', 'safety'), ('diy', 'Do-it-yourself'), ('floor', 'Flooring'), ('plant', 'Plants & gardering'), ('food', 'Food & beverages')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ItemQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(max_length=8, unique=True)),
                ('items', models.ManyToManyField(through='ykea.ItemQuantity', to='ykea.Item')),
            ],
        ),
        migrations.AddField(
            model_name='itemquantity',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ykea.ShoppingCart'),
        ),
        migrations.AddField(
            model_name='itemquantity',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ykea.Item'),
        ),
    ]
