# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ykea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemquantity',
            name='pene',
            field=models.IntegerField(default=23),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
