# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-23 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ykea', '0003_auto_20180518_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='id',
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='cart_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
